# Generated by Django 6.0.1 on 2026-01-30 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Stock ticker symbol (e.g., AAPL, TSLA)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full company name', max_length=255)),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange (e.g., NASDAQ, NYSE)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this stock is actively tracked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current stock price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, help_text='Previous closing price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('change_percent', models.DecimalField(decimal_places=2, help_text='Percentage change (can be negative)', max_digits=6)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], help_text='Overall trend direction', max_length=10)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI-generated explanation of the price movement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.stock')),
            ],
            options={
                'verbose_name': 'Stock Update',
                'verbose_name_plural': 'Stock Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('sms', 'SMS')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Notification message content')),
                ('error_message', models.TextField(blank=True, help_text='Error details if notification failed', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.stock')),
                ('stock_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.stockupdate')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStockPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='How often to receive updates', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether notifications are enabled for this stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stock Preference',
                'verbose_name_plural': 'User Stock Preferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockupdate',
            index=models.Index(fields=['stock', '-created_at'], name='core_stocku_stock_i_36bfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-sent_at'], name='core_notifi_user_id_7710b9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', '-sent_at'], name='core_notifi_status_61aa1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstockpreference',
            unique_together={('user', 'stock')},
        ),
    ]
