# Generated by Django 5.2.11 on 2026-03-08 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockpreference',
            name='threshold_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Alert when price changes by this percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userstockpreference',
            name='notification_frequency',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('monthly', 'Monthly Digest')], default='daily', help_text='How often to receive updates', max_length=15),
        ),
    ]
