# Generated by Django 6.0.1 on 2026-03-04 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional friendly name for this alert', max_length=100)),
                ('alert_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('percent_change_up', 'Percent Change Up'), ('percent_change_down', 'Percent Change Down'), ('volume_spike', 'Volume Spike')], help_text='Type of alert condition', max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=4, help_text='Threshold value (price or percentage depending on alert_type)', max_digits=12)),
                ('time_window', models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', help_text='Time window for percentage-based alerts', max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is enabled')),
                ('is_one_time', models.BooleanField(default=False, help_text='If true, deactivate after first trigger')),
                ('cooldown_minutes', models.PositiveIntegerField(default=60, help_text='Minimum minutes between repeated triggers')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When this alert was last triggered', null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0, help_text='Total times this alert has been triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('alert_analysis', 'Alert Analysis'), ('market_summary', 'Market Summary'), ('news_digest', 'News Digest'), ('price_explanation', 'Price Explanation'), ('portfolio_insight', 'Portfolio Insight')], help_text='Type of prompt/analysis', max_length=20)),
                ('model_name', models.CharField(help_text="LLM model used (e.g., 'gpt-4', 'claude-3-opus')", max_length=50)),
                ('prompt_text', models.TextField(help_text='The prompt sent to the LLM')),
                ('response_text', models.TextField(blank=True, help_text='The response from the LLM', null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Number of input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Number of output tokens')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Response latency in milliseconds')),
                ('is_success', models.BooleanField(default=True, help_text='Whether the LLM call was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the call failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggeredAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_value', models.DecimalField(decimal_places=4, help_text='The actual value when the alert was triggered', max_digits=12)),
                ('threshold_value', models.DecimalField(decimal_places=4, help_text='The threshold value at time of trigger (snapshot)', max_digits=12)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI-generated explanation of why this alert matters', null=True)),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Whether the user has acknowledged this alert')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Triggered Alert',
                'verbose_name_plural': 'Triggered Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone for notifications (e.g., 'America/New_York')", max_length=50)),
                ('email_notifications', models.BooleanField(default=True, help_text='Whether to receive email notifications')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for notifications (Slack, Discord, etc.)', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for signing webhook payloads', max_length=255, null=True)),
                ('daily_alert_limit', models.PositiveIntegerField(default=50, help_text='Maximum alerts per day', validators=[django.core.validators.MaxValueValidator(500)])),
                ('alerts_sent_today', models.PositiveIntegerField(default=0, help_text='Counter for alerts sent today (reset daily)')),
                ('last_alert_reset', models.DateField(auto_now_add=True, help_text='Last date the alert counter was reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='stockupdate',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Stock Update', 'verbose_name_plural': 'Stock Updates'},
        ),
        migrations.RemoveIndex(
            model_name='stockupdate',
            name='core_stocku_stock_i_36bfc2_idx',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the notification was successfully delivered', null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum retry attempts before giving up'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled time for next retry attempt', null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar')], default='USD', help_text='Trading currency', max_length=3),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cached last known price for quick access', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price_updated',
            field=models.DateTimeField(blank=True, help_text='When last_price was last updated', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(blank=True, help_text='Market capitalization in currency units', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, help_text='Industry sector (e.g., Technology, Healthcare)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='close_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Closing price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='data_source',
            field=models.CharField(choices=[('alpha_vantage', 'Alpha Vantage'), ('yahoo', 'Yahoo Finance'), ('polygon', 'Polygon.io'), ('finnhub', 'Finnhub'), ('manual', 'Manual Entry')], default='yahoo', help_text='Source of this price data', max_length=20),
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='high_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Highest price in the period', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='low_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Lowest price in the period', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='open_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Opening price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', help_text='Data timeframe/interval', max_length=5),
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=0, help_text='Actual market timestamp for this data point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='volume',
            field=models.BigIntegerField(default=0, help_text='Trading volume', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry Scheduled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='stock_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.stockupdate'),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='change_percent',
            field=models.DecimalField(decimal_places=4, help_text='Percentage change (can be negative)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Previous closing price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='Current/closing stock price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='core_stock_sector_5d7e70_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange'], name='core_stock_exchang_451c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockupdate',
            index=models.Index(fields=['stock', '-timestamp'], name='core_stocku_stock_i_e1581b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockupdate',
            index=models.Index(fields=['stock', 'timeframe', '-timestamp'], name='core_stocku_stock_i_bfef1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockupdate',
            constraint=models.UniqueConstraint(fields=('stock', 'timestamp', 'timeframe'), name='unique_stock_timestamp_timeframe'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.stock'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='Related stock if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to='core.stock'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who initiated this request (null for system calls)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggeredalert',
            name='alert_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_alerts', to='core.alertrule'),
        ),
        migrations.AddField(
            model_name='triggeredalert',
            name='stock_update',
            field=models.ForeignKey(blank=True, help_text='The stock update that triggered this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='core.stockupdate'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='triggered_alert',
            field=models.ForeignKey(blank=True, help_text='Related triggered alert if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to='core.triggeredalert'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='triggered_alert',
            field=models.ForeignKey(blank=True, help_text='The triggered alert that caused this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.triggeredalert'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'next_retry_at'], name='core_notifi_status_fba191_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['user', 'is_active'], name='core_alertr_user_id_c7f2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['stock', 'is_active', 'alert_type'], name='core_alertr_stock_i_7b5500_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredalert',
            index=models.Index(fields=['alert_rule', '-created_at'], name='core_trigge_alert_r_49d41e_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['user', '-created_at'], name='core_llmusa_user_id_78cc13_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['prompt_type', '-created_at'], name='core_llmusa_prompt__c26e50_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusagelog',
            index=models.Index(fields=['model_name', '-created_at'], name='core_llmusa_model_n_0e0b85_idx'),
        ),
    ]
