# Generated by Django 6.0.1 on 2026-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alertrule_llmusagelog_triggeredalert_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', help_text='User role: admin has full access, user has standard access', max_length=10),
        ),
    ]
